
[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "curl"]

[phases.install]
cmds = ["npm install", "npm install express-cors"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"

[env]
NODE_ENV = "production"
PORT = "8080"

# Add CORS headers configuration
CORS_ALLOW_ORIGIN = "*"
