// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owvyvalwbbyrbzxlwjeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dnl2YWx3YmJ5cmJ6eGx3amVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Mzg5MzIsImV4cCI6MjA2MTIxNDkzMn0.n3vFK4kQVdP19SlTMi3frQYI8yuCeoRabGbgey6k4sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);